apiVersion: v1
kind: Service
metadata:
  name: mcart-catalogservice
  namespace: default
spec:
  selector:
    app: mcart-catalogservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
