apiVersion: v1
kind: Service
metadata:
  name: mcart-catalogservice
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: mcart-catalogservice
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080