name: Deploy to Kubernetes

on:
  workflow_dispatch:  # Allow manual triggering

  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: prasadbhalerao
  CONTAINER_NAME: mcart-catalogservice
  RESOURCE_GROUP: Mcart-RG
  CLUSTER_NAME: Mcart-AKS-Cluster

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -f ./CatalogService/dockerfile -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }} .
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy to AKS
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Set Azure Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }} --overwrite-existing

      - name: Set KUBECONFIG
        run: |
          export KUBECONFIG=$HOME/.kube/config

      - name: Debug Kubernetes Context
        run: |
          kubectl config view
          kubectl config current-context
          kubectl get nodes
          
      # Apply Kubernetes Manifests
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f manifests/

      # Verify Deployment Status
      - name: Check Deployment Status
        run: |
          kubectl rollout status deployment/mcart-catalogservice
